version: '3'
services:
  sync:
    image: concordconsortium/docker-volume-sync
    volumes:
      - type: volume
        source: 'jg-corpus-data'
        target: /data
      - type: bind
        source: ./jg-corpus-data
        target: /host_data
  app:
    build:
      context: .
    entrypoint: ["/bin/bash", "/usr/local/bin/wait-for-it.sh", "sync:5001", "-s", "-t", "30", "--"]
    command: ["echo", "jg-corpus-data is synchronized"]
    depends_on: [ sync ]

volumes:
  jg-corpus-data: { external: true }