# Copyright 2021 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"

services:

  # tag::jg_client[]
  jg-client:
    labels:
      edu.vanderbilt.isis.lab: "mesolab"
    image: ${dockerImage}
    command:
      - "./bin/gremlin.sh"
    container_name: jg-client
    environment:
      GREMLIN_REMOTE_HOSTS: "jce-jg"
    networks:
      - jg-network
    volumes:
      - type: volume
        source: "jg-scripts"
        target: /opt/janusgraph/scripts
        read_only: true
      - type: volume
        source: "jg-product-data"
        target: /opt/janusgraph/product
# end::jg_client[]

# https://docs.docker.com/compose/networking/
networks:
  jg-network:
    name: jg-network

# tag::volumes[]
volumes:
  jg-scripts: { external: true }
  jg-product-data: { external: true }
# end::volumes[]
